# SimpleTimeService for AWS Lambda (Task 2)
FROM public.ecr.aws/lambda/python:3.12

LABEL description="SimpleTimeService"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

CMD ["main.handler"]

